# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='ParsedQuestion',
            fields=[
                ('content', models.CharField(default=b' ', max_length=100, primary_key=True, serialize=False)),
                ('parsed_result', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
        migrations.AddField(
            model_name='question',
            name='confidence_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='result',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.ForeignKey(default=b' ', on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to='game.ParsedQuestion'),
        ),
        migrations.AddField(
            model_name='question',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.Game'),
        ),
    ]
