# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170206_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='result',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
