# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170215_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='confidence_score',
            field=models.FloatField(default=0),
        ),
    ]
