# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170215_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
