# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_question_created_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Original_Question',
            fields=[
                ('content', models.CharField(default=b' ', max_length=100, primary_key=True, serialize=False)),
                ('parsed_result', models.CharField(blank=True, max_length=200)),
                ('label', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='ParsedQuestion',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='game_id',
            new_name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='hint_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='original_questions',
            field=models.ManyToManyField(to='game.Original_Question'),
        ),
    ]
