# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-02-20 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_original_question_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='name_en',
            field=models.CharField(default=b'NULL', max_length=20),
        ),
    ]
