# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_answer_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hint_used',
            field=models.CharField(default=b'None', max_length=20),
        ),
    ]
