# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-26 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20170329_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_label',
            field=models.NullBooleanField(),
        ),
    ]
